run_notes: "quick gpu test"

models:
  - model001
  - model002

train_on:
  - gtzan

test_on:
  - gtzan

num_classes: 10
batch_size: 32
epochs: 5
lr: 0.0001
scheduler: plateau
early_stopping_patience: 999
img_size: 224
num_workers: 4

gtzan_labels: data/GTZAN/spectrogramsManuel/labels.csv
gtzan_img_dir: data/GTZAN/spectrogramsManuel
fma_labels: data/FMA_Small/spectrogramsManuel/labels.csv
fma_img_dir: data/FMA_Small/spectrogramsManuel
