run_notes: "pipeline test - 2 models, 2 datasets, 2 epochs"

models:
  - model001
  - model002

train_on:
  - gtzan
  - fma

test_on:
  - gtzan
  - fma

num_classes: 13
batch_size: 16
epochs: 2
lr: 0.001
scheduler: plateau
early_stopping_patience: 999
img_size: 224
num_workers: 2

gtzan_labels: data/GTZAN/spectrogramsManuel/labels.csv
gtzan_img_dir: data/GTZAN/spectrogramsManuel
fma_labels: data/FMA_Small/spectrogramsManuel/labels.csv
fma_img_dir: data/FMA_Small/spectrogramsManuel
